In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('all/train-set.csv')

In [2]:
df.head(10)

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0   1       2611     326     20                               120   
1   2       2772     324     17                                42   
2   3       2764       4     14                               480   
3   4       3032     342      9                                60   
4   5       2488      23     11                               117   
5   6       2968      83      8                               390   
6   7       3027      11      6                               534   
7   8       3216     277      9                                67   
8   9       3242     262      5                               849   
9  10       3315      61     15                               120   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                              27                             1597   
1                               7                             1814   
2                             -21                              700   
3                               8                             4050   
4                              21                             1117   
5                              19                             4253   
6                              47                             1248   
7                              23                             5430   
8                             169                             1672   
9                              -6                             3042   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm     ...      Soil_Type32  \
0            168             214            184     ...                0   
1            175             220            183     ...                0   
2            201             212            148     ...                0   
3            202             227            164     ...                0   
4            209             218            151     ...                0   
5            232             226            127     ...                0   
6            214             228            151     ...                0   
7            212             236            169     ...                0   
8            207             242            173     ...                0   
9            231             208            106     ...                0   

   Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   
5            0            0            0            0            0   
6            0            0            0            0            0   
7            0            0            0            0            0   
8            0            0            0            0            0   
9            0            0            0            0            0   

   Soil_Type38  Soil_Type39  Soil_Type40  Cover_Type  
0            0            0            0           6  
1            0            0            0           2  
2            0            0            0           2  
3            0            0            0           2  
4            0            0            0           2  
5            0            0            0           2  
6            0            0            0           2  
7            0            0            0           1  
8            0            0            0           1  
9            1            0            0           7  

[10 rows x 56 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528720 entries, 0 to 528719
Data columns (total 56 columns):
Id                                    528720 non-null int64
Elevation                             528720 non-null int64
Aspect                                528720 non-null int64
Slope                                 528720 non-null int64
Horizontal_Distance_To_Hydrology      528720 non-null int64
Vertical_Distance_To_Hydrology        528720 non-null int64
Horizontal_Distance_To_Roadways       528720 non-null int64
Hillshade_9am                         528720 non-null int64
Hillshade_Noon                        528720 non-null int64
Hillshade_3pm                         528720 non-null int64
Horizontal_Distance_To_Fire_Points    528720 non-null int64
Wilderness_Area1                      528720 non-null int64
Wilderness_Area2                      528720 non-null int64
Wilderness_Area3                      528720 non-null int64
Wilderness_Area4                      528720 non-

In [75]:
train_data = df.values

In [76]:
print(train_data)

[[     1   2611    326 ...      0      0      6]
 [     2   2772    324 ...      0      0      2]
 [     3   2764      4 ...      0      0      2]
 ...
 [528718   3169    168 ...      0      0      2]
 [528719   3145    283 ...      0      0      1]
 [528720   3177    156 ...      0      0      2]]


In [77]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 10)

In [88]:
model = model.fit(train_data[0:,1:-1],train_data[0:,-1])

In [89]:
df_test = pd.read_csv('all/test-set.csv')

In [90]:
df_test.head(10)

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0  528721       2953     224      9                                55   
1  528722       2977     233     14                                42   
2  528723       3055     227      9                               120   
3  528724       2615     107     13                               277   
4  528725       3033      59     15                               457   
5  528726       3054     336     12                               381   
6  528727       3094       9      9                               424   
7  528728       2010      84     35                               300   
8  528729       2672     338     25                                60   
9  528730       2929      88      8                                42   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                              11                             1600   
1                               1                             1282   
2                               5                             2724   
3                              74                              967   
4                              94                             4086   
5                              80                             3277   
6                             -80                             1470   
7                             143                              330   
8                              33                             1422   
9                               0                             3515   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm     ...       Soil_Type31  \
0            206             251            176     ...                 0   
1            196             252            192     ...                 0   
2            207             249            178     ...                 0   
3            241             224            110     ...                 0   
4            233             213             99     ...                 0   
5            193             229            179     ...                 1   
6            210             222            149     ...                 0   
7            244             158             13     ...                 0   
8            158             196            172     ...                 0   
9            233             227            126     ...                 0   

   Soil_Type32  Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  \
0            1            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   
5            0            0            0            0            0   
6            0            0            0            0            0   
7            0            0            0            0            0   
8            0            1            0            0            0   
9            0            0            0            0            0   

   Soil_Type37  Soil_Type38  Soil_Type39  Soil_Type40  
0            0            0            0            0  
1            0            0            0            0  
2            0            0            0            0  
3            0            0            0            0  
4            0            0            0            0  
5            0            0            0            0  
6            0            0            0            0  
7            0            0            0            0  
8            0            0            0            0  
9            0            0            0            0  

[10 rows x 55 columns]

In [92]:
test_data = df_test.values

In [94]:
output = model.predict(test_data[:,1:])

In [95]:
print(output)

[2 2 1 ... 7 3 2]


In [96]:
from sklearn.metrics import accuracy_score

In [97]:
result = np.c_[test_data[:,0].astype(int), output.astype(int)]
df_result = pd.DataFrame(result[:,0:2], columns=['Id', 'Cover_Type'])

In [99]:
print(df_result)

            Id  Cover_Type
0       528721           2
1       528722           2
2       528723           1
3       528724           2
4       528725           1
5       528726           2
6       528727           1
7       528728           3
8       528729           2
9       528730           1
10      528731           2
11      528732           1
12      528733           2
13      528734           3
14      528735           5
15      528736           1
16      528737           1
17      528738           1
18      528739           2
19      528740           2
20      528741           1
21      528742           2
22      528743           1
23      528744           1
24      528745           1
25      528746           2
26      528747           1
27      528748           2
28      528749           1
29      528750           1
...        ...         ...
226565  755286           2
226566  755287           3
226567  755288           1
226568  755289           2
226569  755290           1
2

In [100]:
df_result.to_csv('all/forest.csv', index=False)

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import ExtraTreesClassifier

train_df = pd.read_csv('all/train-set.csv')
test_df = pd.read_csv('all/test-set.csv')

def change_feature(data_input):
    data = data_input
    data['Ele_minus_VDtHyd'] = data.Elevation - data.Vertical_Distance_To_Hydrology
    data['Ele_plus_VDtHyd'] = data.Elevation + data.Vertical_Distance_To_Hydrology
    data['Distanse_to_Hydrolody'] = (data['Horizontal_Distance_To_Hydrology'] ** 2 + data['Vertical_Distance_To_Hydrology'] ** 2) ** 0.5
    data['Hydro_plus_Fire'] = data['Horizontal_Distance_To_Hydrology'] + data['Horizontal_Distance_To_Fire_Points']
    data['Hydro_minus_Fire'] = data['Horizontal_Distance_To_Hydrology'] - data['Horizontal_Distance_To_Fire_Points']
    data['Hydro_plus_Road'] = data['Horizontal_Distance_To_Hydrology'] + data['Horizontal_Distance_To_Roadways']
    data['Hydro_minus_Road'] = data['Horizontal_Distance_To_Hydrology'] - data['Horizontal_Distance_To_Roadways']
    data['Fire_plus_Road'] = data['Horizontal_Distance_To_Fire_Points'] + data['Horizontal_Distance_To_Roadways']
    data['Fire_minus_Road'] = data['Horizontal_Distance_To_Fire_Points'] - data['Horizontal_Distance_To_Roadways']
    data['Soil'] = 0
    for i in range(1, 41):
        data['Soil'] = data['Soil'] + i * data['Soil_Type' + str(i)]
    data['Wilderness_Area'] = 0
    for i in range(1, 5):
        data['Wilderness_Area'] = data['Wilderness_Area'] + i * data['Wilderness_Area' + str(i)]
    for i in range(1, 41):
        data = data.drop(['Soil_Type' + str(i)], axis=1)
    for i in range(1, 5):
        data = data.drop(['Wilderness_Area' + str(i)], axis=1)
    return data

def get_features():
    return ['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology',
            'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm',
            'Horizontal_Distance_To_Fire_Points',
            'Ele_minus_VDtHyd', 'Ele_plus_VDtHyd', 'Distanse_to_Hydrolody', 'Hydro_plus_Fire', 'Hydro_minus_Fire',
            'Hydro_plus_Road',
            'Hydro_minus_Road', 'Fire_plus_Road', 'Fire_minus_Road', 'Soil', 'Wilderness_Area']

train_df = change_feature(train_df)
test_df = change_feature(test_df)

features = get_features()

y_train = train_df['Cover_Type'].values
test_id = test_df['Id']
X_train = train_df[:][features].values
X_test = test_df[:][features].values


print('Start')

clf = ExtraTreesClassifier(max_features=0.3, n_estimators=500)
clf.fit(X_train, y_train)

print('train over')

output = clf.predict(X_test)


# submission = pd.DataFrame(data={'Id': test_id, 'Cover_Type': y_predict})
# submission.to_csv("submission.csv", index=False)



result = np.c_[test_id.astype(int), output.astype(int)]
df_result = pd.DataFrame(result[:,0:2], columns=['Id', 'Cover_Type'])
df_result.to_csv('all/forest.csv', index=False)

print('Compelte')



