In [155]:
import pandas as pd
import numpy as np

df = pd.read_csv('all/train-set.csv')

In [156]:
df.head(10)

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0   1       2611     326     20                               120   
1   2       2772     324     17                                42   
2   3       2764       4     14                               480   
3   4       3032     342      9                                60   
4   5       2488      23     11                               117   
5   6       2968      83      8                               390   
6   7       3027      11      6                               534   
7   8       3216     277      9                                67   
8   9       3242     262      5                               849   
9  10       3315      61     15                               120   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                              27                             1597   
1                               7                             1814   
2                             -21                              700   
3                               8                             4050   
4                              21                             1117   
5                              19                             4253   
6                              47                             1248   
7                              23                             5430   
8                             169                             1672   
9                              -6                             3042   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm     ...      Soil_Type32  \
0            168             214            184     ...                0   
1            175             220            183     ...                0   
2            201             212            148     ...                0   
3            202             227            164     ...                0   
4            209             218            151     ...                0   
5            232             226            127     ...                0   
6            214             228            151     ...                0   
7            212             236            169     ...                0   
8            207             242            173     ...                0   
9            231             208            106     ...                0   

   Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   
5            0            0            0            0            0   
6            0            0            0            0            0   
7            0            0            0            0            0   
8            0            0            0            0            0   
9            0            0            0            0            0   

   Soil_Type38  Soil_Type39  Soil_Type40  Cover_Type  
0            0            0            0           6  
1            0            0            0           2  
2            0            0            0           2  
3            0            0            0           2  
4            0            0            0           2  
5            0            0            0           2  
6            0            0            0           2  
7            0            0            0           1  
8            0            0            0           1  
9            1            0            0           7  

[10 rows x 56 columns]

In [157]:
# df['Elevation']=df['Elevation'].map(lambda x: 'x' if x<3100 and x>2900 else '7' if x<3200 and x>3100 else '6')
# df = pd.get_dummies(df)
# df.info()
# df.head(10)

In [158]:
train_data = df.values
soil_data = train_data[:,-41:-1]
wild_data = train_data[:,11:14]
print(soil_data[:10,:])
print(wild_data[:10,:])
# for i in range(0,len)
for k in range(0,train_data.shape[0]):
    soil_data[k,:] = np.argmax(soil_data[k,:])
    wild_data[k,:] = np.argmax(wild_data[k,:])
# soil_data = soil_data[:,0]
# print(soil_data.shape[0])
temp_data = np.column_stack((train_data[:,:11],wild_data[:,0]))
temp_data = np.column_stack((temp_data[:,:],soil_data[:,0]))
train_data = np.column_stack((temp_data[:,:],train_data[:,-1]))
print(train_data[0:10,:])

[[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0]]
[[0 0 1]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]]
[[   1 2611  326   20  120   27 1597  168  214  184 2913  

In [159]:
print(train_data)

[[     1   2611    326 ...      2      9      6]
 [     2   2772    324 ...      0     22      2]
 [     3   2764      4 ...      2     10      2]
 ...
 [528718   3169    168 ...      1     21      2]
 [528719   3145    283 ...      1     23      1]
 [528720   3177    156 ...      2     31      2]]


In [160]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators = 100)

In [161]:
model = model.fit(train_data[0:,1:-1],train_data[0:,-1])

In [162]:
df_test = pd.read_csv('all/test-set.csv')
# df_test['Elevation']=df_test['Elevation'].map(lambda x: 'x' if x<3100 and x>2900 else '7' if x<3200 and x>3100 else '6')
# df_test = pd.get_dummies(df_test)

In [163]:
df_test.head(10)

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0  528721       2953     224      9                                55   
1  528722       2977     233     14                                42   
2  528723       3055     227      9                               120   
3  528724       2615     107     13                               277   
4  528725       3033      59     15                               457   
5  528726       3054     336     12                               381   
6  528727       3094       9      9                               424   
7  528728       2010      84     35                               300   
8  528729       2672     338     25                                60   
9  528730       2929      88      8                                42   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                              11                             1600   
1                               1                             1282   
2                               5                             2724   
3                              74                              967   
4                              94                             4086   
5                              80                             3277   
6                             -80                             1470   
7                             143                              330   
8                              33                             1422   
9                               0                             3515   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm     ...       Soil_Type31  \
0            206             251            176     ...                 0   
1            196             252            192     ...                 0   
2            207             249            178     ...                 0   
3            241             224            110     ...                 0   
4            233             213             99     ...                 0   
5            193             229            179     ...                 1   
6            210             222            149     ...                 0   
7            244             158             13     ...                 0   
8            158             196            172     ...                 0   
9            233             227            126     ...                 0   

   Soil_Type32  Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  \
0            1            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   
5            0            0            0            0            0   
6            0            0            0            0            0   
7            0            0            0            0            0   
8            0            1            0            0            0   
9            0            0            0            0            0   

   Soil_Type37  Soil_Type38  Soil_Type39  Soil_Type40  
0            0            0            0            0  
1            0            0            0            0  
2            0            0            0            0  
3            0            0            0            0  
4            0            0            0            0  
5            0            0            0            0  
6            0            0            0            0  
7            0            0            0            0  
8            0            0            0            0  
9            0            0            0            0  

[10 rows x 55 columns]

In [164]:
test_data = df_test.values
soil_data = test_data[:,-40:]
wild_data = test_data[:,11:14]
print(soil_data[:10,:])
print(wild_data[:10,:])
# for i in range(0,len)
for k in range(0,test_data.shape[0]):
    soil_data[k,:] = np.argmax(soil_data[k,:])
    wild_data[k,:] = np.argmax(wild_data[k,:])
# soil_data = soil_data[:,0]
# print(soil_data.shape[0])
temp_data = np.column_stack((test_data[:,:11],wild_data[:,0]))
test_data = np.column_stack((temp_data[:,:],soil_data[:,0]))
print(test_data[0:10,:])

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
  0 0 0 0]]
[[0 0 1]
 [0 0 1]
 [0 0 1]
 [1 0 0]
 [1 0 0]
 [0 0 1]
 [1 0 0]
 [0 0 0]
 [0 0 1]
 [1 0 0]]
[[528721   2953    224      9     55     11   1600    206 

In [165]:
print(test_data[0:10,:])

[[528721   2953    224      9     55     11   1600    206    251    176
    1669      2     31]
 [528722   2977    233     14     42      1   1282    196    252    192
     277      2     22]
 [528723   3055    227      9    120      5   2724    207    249    178
     908      2     22]
 [528724   2615    107     13    277     74    967    241    224    110
    3545      0     28]
 [528725   3033     59     15    457     94   4086    233    213     99
    4974      0     28]
 [528726   3054    336     12    381     80   3277    193    229    179
    1009      2     30]
 [528727   3094      9      9    424    -80   1470    210    222    149
    1165      0     28]
 [528728   2010     84     35    300    143    330    244    158     13
    1001      0      2]
 [528729   2672    338     25     60     33   1422    158    196    172
    1214      2     32]
 [528730   2929     88      8     42      0   3515    233    227    126
    2730      0     28]]


In [166]:
output = model.predict(test_data[:,1:])

In [167]:
print(output)

[2 2 1 ... 7 3 2]


In [168]:
from sklearn.metrics import accuracy_score

In [169]:
result = np.c_[test_data[:,0].astype(int), output.astype(int)]
df_result = pd.DataFrame(result[:,0:2], columns=['Id', 'Cover_Type'])

In [170]:
print(df_result)

            Id  Cover_Type
0       528721           2
1       528722           2
2       528723           1
3       528724           2
4       528725           1
5       528726           2
6       528727           1
7       528728           3
8       528729           2
9       528730           2
10      528731           2
11      528732           1
12      528733           2
13      528734           3
14      528735           5
15      528736           1
16      528737           1
17      528738           1
18      528739           2
19      528740           2
20      528741           1
21      528742           2
22      528743           1
23      528744           1
24      528745           1
25      528746           2
26      528747           2
27      528748           2
28      528749           1
29      528750           1
...        ...         ...
226565  755286           2
226566  755287           3
226567  755288           1
226568  755289           3
226569  755290           1
2

In [171]:
df_result.to_csv('all/forest.csv', index=False)