In [14]:
import pandas as pd
import numpy as np

df = pd.read_csv('all/train-set.csv')

In [15]:
df.head(10)

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0   1       2611     326     20                               120   
1   2       2772     324     17                                42   
2   3       2764       4     14                               480   
3   4       3032     342      9                                60   
4   5       2488      23     11                               117   
5   6       2968      83      8                               390   
6   7       3027      11      6                               534   
7   8       3216     277      9                                67   
8   9       3242     262      5                               849   
9  10       3315      61     15                               120   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                              27                             1597   
1                               7                             1814   
2                             -21                              700   
3                               8                             4050   
4                              21                             1117   
5                              19                             4253   
6                              47                             1248   
7                              23                             5430   
8                             169                             1672   
9                              -6                             3042   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm     ...      Soil_Type32  \
0            168             214            184     ...                0   
1            175             220            183     ...                0   
2            201             212            148     ...                0   
3            202             227            164     ...                0   
4            209             218            151     ...                0   
5            232             226            127     ...                0   
6            214             228            151     ...                0   
7            212             236            169     ...                0   
8            207             242            173     ...                0   
9            231             208            106     ...                0   

   Soil_Type33  Soil_Type34  Soil_Type35  Soil_Type36  Soil_Type37  \
0            0            0            0            0            0   
1            0            0            0            0            0   
2            0            0            0            0            0   
3            0            0            0            0            0   
4            0            0            0            0            0   
5            0            0            0            0            0   
6            0            0            0            0            0   
7            0            0            0            0            0   
8            0            0            0            0            0   
9            0            0            0            0            0   

   Soil_Type38  Soil_Type39  Soil_Type40  Cover_Type  
0            0            0            0           6  
1            0            0            0           2  
2            0            0            0           2  
3            0            0            0           2  
4            0            0            0           2  
5            0            0            0           2  
6            0            0            0           2  
7            0            0            0           1  
8            0            0            0           1  
9            1            0            0           7  

[10 rows x 56 columns]

In [16]:
train_data = df.values

In [17]:
print(train_data)

[[     1   2611    326 ...      0      0      6]
 [     2   2772    324 ...      0      0      2]
 [     3   2764      4 ...      0      0      2]
 ...
 [528718   3169    168 ...      0      0      2]
 [528719   3145    283 ...      0      0      1]
 [528720   3177    156 ...      0      0      2]]


In [18]:
# from sklearn.ensemble import RandomForestClassifier
# model = RandomForestClassifier(n_estimators = 10)
from sklearn import svm
model = svm.SVC(gamma=0.001, C=100.)

In [ ]:
model = model.fit(train_data[0:-1000,1:-1],train_data[0:-1000,-1])

In [ ]:
test_data = train_data[-1000:,1:-1]

In [ ]:
output = model.predict(test_data)

In [ ]:
print(output)

In [ ]:
standard = train_data[-1000:,-1]

In [ ]:
print(standard)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(standard,output)

In [ ]:
print(accuracy)

In [1]:
import pandas as pd
import numpy as np

# Load the train set and the test set
train_df = pd.read_csv('all/train-set.csv')
test_df = pd.read_csv('all/test-set.csv')

train_df.info()
test_df.info()

train_df.head(10)
test_df.head(10)

# Change some attributes of the set in order to have a bette result in the classifier
def change_feature(data_input):
    data = data_input
    data['Ele_minus_VDH'] = data.Elevation - data.Vertical_Distance_To_Hydrology
    data['Ele_plus_VDH'] = data.Elevation + data.Vertical_Distance_To_Hydrology
    # Add some relation between Elevation and Vertical_Distance_To_Hydrology
    data['Distanse_to_Hydrolody'] = (data['Horizontal_Distance_To_Hydrology'] ** 2 + data['Vertical_Distance_To_Hydrology'] ** 2) ** 0.5
    # Calculate the relative distance 
    data['Hydro_plus_Fire'] = data['Horizontal_Distance_To_Hydrology'] + data['Horizontal_Distance_To_Fire_Points']
    data['Hydro_minus_Fire'] = data['Horizontal_Distance_To_Hydrology'] - data['Horizontal_Distance_To_Fire_Points']
    data['Hydro_plus_Road'] = data['Horizontal_Distance_To_Hydrology'] + data['Horizontal_Distance_To_Roadways']
    data['Hydro_minus_Road'] = data['Horizontal_Distance_To_Hydrology'] - data['Horizontal_Distance_To_Roadways']
    data['Fire_plus_Road'] = data['Horizontal_Distance_To_Fire_Points'] + data['Horizontal_Distance_To_Roadways']
    data['Fire_minus_Road'] = data['Horizontal_Distance_To_Fire_Points'] - data['Horizontal_Distance_To_Roadways']
    # Some relations of hydrology, fire point and road

    # Because there a 40 attributes for the soil and 4 attributes for the wilderness area and those values are binary
    # In fact they have only attribute valued 1 and the others are 0 so if we delete them and create a new attribute with int type, the data set will be more precise
    # 
    data['Soil'] = 0
    for i in range(1, 41):
        data['Soil'] = data['Soil'] + i * data['Soil_Type' + str(i)]
    data['Wilderness_Area'] = 0
    for i in range(1, 5):
        data['Wilderness_Area'] = data['Wilderness_Area'] + i * data['Wilderness_Area' + str(i)]
    for i in range(1, 41):
        data = data.drop(['Soil_Type' + str(i)], axis=1)
    for i in range(1, 5):
        data = data.drop(['Wilderness_Area' + str(i)], axis=1)
    return data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528720 entries, 0 to 528719
Data columns (total 56 columns):
Id                                    528720 non-null int64
Elevation                             528720 non-null int64
Aspect                                528720 non-null int64
Slope                                 528720 non-null int64
Horizontal_Distance_To_Hydrology      528720 non-null int64
Vertical_Distance_To_Hydrology        528720 non-null int64
Horizontal_Distance_To_Roadways       528720 non-null int64
Hillshade_9am                         528720 non-null int64
Hillshade_Noon                        528720 non-null int64
Hillshade_3pm                         528720 non-null int64
Horizontal_Distance_To_Fire_Points    528720 non-null int64
Wilderness_Area1                      528720 non-null int64
Wilderness_Area2                      528720 non-null int64
Wilderness_Area3                      528720 non-null int64
Wilderness_Area4                      528720 non-

In [2]:
train_df = change_feature(train_df)

In [4]:
train_df.head(10)

Id  Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0   1       2611     326     20                               120   
1   2       2772     324     17                                42   
2   3       2764       4     14                               480   
3   4       3032     342      9                                60   
4   5       2488      23     11                               117   
5   6       2968      83      8                               390   
6   7       3027      11      6                               534   
7   8       3216     277      9                                67   
8   9       3242     262      5                               849   
9  10       3315      61     15                               120   

   Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                              27                             1597   
1                               7                             1814   
2                             -21                              700   
3                               8                             4050   
4                              21                             1117   
5                              19                             4253   
6                              47                             1248   
7                              23                             5430   
8                             169                             1672   
9                              -6                             3042   

   Hillshade_9am  Hillshade_Noon  Hillshade_3pm       ...         \
0            168             214            184       ...          
1            175             220            183       ...          
2            201             212            148       ...          
3            202             227            164       ...          
4            209             218            151       ...          
5            232             226            127       ...          
6            214             228            151       ...          
7            212             236            169       ...          
8            207             242            173       ...          
9            231             208            106       ...          

   Ele_plus_VDH  Distanse_to_Hydrolody  Hydro_plus_Fire  Hydro_minus_Fire  \
0          2638             123.000000             3033             -2793   
1          2779              42.579338             2921             -2837   
2          2743             480.459155             1180              -220   
3          3040              60.530984             2436             -2316   
4          2509             118.869677             1253             -1019   
5          2987             390.462546             4960             -4180   
6          3074             536.064362             2922             -1854   
7          3239              70.837843             2440             -2306   
8          3411             865.656976             1540               158   
9          3309             120.149906             1952             -1712   

   Hydro_plus_Road  Hydro_minus_Road  Fire_plus_Road  Fire_minus_Road  Soil  \
0             1717             -1477            4510             1316    10   
1             1856             -1772            4693             1065    23   
2             1180              -220            1400                0    11   
3             4110             -3990            6426            -1674    23   
4             1234             -1000            2253               19     6   
5             4643             -3863            8823              317    12   
6             1782              -714            3636             1140    29   
7             5497             -5363            7803            -3057    22   
8             2521              -823            2363             -981    24   
9             3162             -2922            4874            -1210    38   

   Wi

In [19]:
import pandas as pd
import numpy as np
import math

def learn_head(inputs):

    inputs['Distance_To_Hydrolody'] =(inputs['Horizontal_Distance_To_Hydrology'] ** 2 
        + inputs['Vertical_Distance_To_Hydrology'] ** 2) ** 0.5
    inputs['Distance_To_Roadways'] = inputs['Horizontal_Distance_To_Roadways'] * inputs['Slope']
    inputs['Distance_To_Fire_Points'] = inputs['Horizontal_Distance_To_Fire_Points'] * inputs['Slope']
    inputs['Soil_Type'] = 0
    for i in range(1, 41):
        inputs['Soil_Type'] = inputs['Soil_Type'] + i * inputs['Soil_Type' + str(i)]
    for i in range(1, 41):
        inputs = inputs.drop(['Soil_Type' + str(i)], axis=1)
    inputs['Wilderness_Area'] = 0
    for i in range(1, 5):
        inputs['Wilderness_Area'] = inputs['Wilderness_Area'] + i * inputs['Wilderness_Area' + str(i)]
    for i in range(1, 5):
        inputs = inputs.drop(['Wilderness_Area' + str(i)], axis=1)
    inputs.drop(['Slope'], axis = 1)
    inputs.drop(['Horizontal_Distance_To_Hydrology'], axis = 1)
    inputs.drop(['Vertical_Distance_To_Hydrology'], axis = 1)
    inputs.drop(['Horizontal_Distance_To_Roadways'], axis = 1)
    inputs.drop(['Horizontal_Distance_To_Fire_Points'], axis = 1)
    return inputs

df_train = pd.read_csv('all/train-set.csv')
df_test = pd.read_csv('all/test-set.csv')

df_train = learn_head(df_train)
df_test = learn_head(df_test)
y_train = df_train['Cover_Type'].values
df_train = df_train.drop(['Cover_Type'], axis = 1)
train_value = df_train.values
# train_X = train_value[ : , : -1]
# train_Y = train_value[ : , -1: ]

# local_X = train_value[ : , : -1]
# local_Y = train_value[ : , -1: ]

# indices = np.random.permutation(len(local_X))
# train_X = local_X[indices[ : -10000]]
# train_Y = local_Y[indices[ : -10000]]
# test_X = local_X[indices[-10000 : ]]
# test_Y = local_Y[indices[-10000 : ]]

# test_X = df_test.values




In [21]:
print(train_value[-10000:,:])
df_train.info()

[[5.18721e+05 2.76800e+03 2.90000e+01 ... 5.28480e+04 2.90000e+01
  1.00000e+00]
 [5.18722e+05 3.01700e+03 1.26000e+02 ... 3.68480e+04 1.20000e+01
  1.00000e+00]
 [5.18723e+05 3.17500e+03 3.58000e+02 ... 5.94540e+04 2.40000e+01
  3.00000e+00]
 ...
 [5.28718e+05 3.16900e+03 1.68000e+02 ... 6.94650e+04 2.20000e+01
  2.00000e+00]
 [5.28719e+05 3.14500e+03 2.83000e+02 ... 1.10790e+04 2.40000e+01
  2.00000e+00]
 [5.28720e+05 3.17700e+03 1.56000e+02 ... 4.30360e+04 3.20000e+01
  3.00000e+00]]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528720 entries, 0 to 528719
Data columns (total 16 columns):
Id                                    528720 non-null int64
Elevation                             528720 non-null int64
Aspect                                528720 non-null int64
Slope                                 528720 non-null int64
Horizontal_Distance_To_Hydrology      528720 non-null int64
Vertical_Distance_To_Hydrology        528720 non-null int64
Horizontal_Distance_To_Roadways      

In [22]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier()
rf.fit(train_value[:-10000,:], y_train[:-10000])
result = rf.predict(train_value[-10000:,:])

from sklearn.metrics import accuracy_score

print("accuracy_score = ", accuracy_score(y_train[-10000:], result))

accuracy_score =  0.9237


In [23]:
import pandas as pd
import numpy as np

# Load the train set and the test set
train_df = pd.read_csv('all/train-set.csv')
test_df = pd.read_csv('all/test-set.csv')

train_df.info()
test_df.info()

train_df.head(10)
test_df.head(10)

# Change some attributes of the set in order to have a bette result in the classifier
def change_feature(data_input):
    data = data_input
    data['Ele_minus_VDH'] = data.Elevation - data.Vertical_Distance_To_Hydrology
    data['Ele_plus_VDH'] = data.Elevation + data.Vertical_Distance_To_Hydrology
    # Add some relation between Elevation and Vertical_Distance_To_Hydrology
    data['Distanse_to_Hydrolody'] = (data['Horizontal_Distance_To_Hydrology'] ** 2 + data['Vertical_Distance_To_Hydrology'] ** 2) ** 0.5
    # Calculate the relative distance 
    data['Hydro_plus_Fire'] = data['Horizontal_Distance_To_Hydrology'] + data['Horizontal_Distance_To_Fire_Points']
    data['Hydro_minus_Fire'] = data['Horizontal_Distance_To_Hydrology'] - data['Horizontal_Distance_To_Fire_Points']
    data['Hydro_plus_Road'] = data['Horizontal_Distance_To_Hydrology'] + data['Horizontal_Distance_To_Roadways']
    data['Hydro_minus_Road'] = data['Horizontal_Distance_To_Hydrology'] - data['Horizontal_Distance_To_Roadways']
    data['Fire_plus_Road'] = data['Horizontal_Distance_To_Fire_Points'] + data['Horizontal_Distance_To_Roadways']
    data['Fire_minus_Road'] = data['Horizontal_Distance_To_Fire_Points'] - data['Horizontal_Distance_To_Roadways']
    # Some relations of hydrology, fire point and road

    # Because there a 40 attributes for the soil and 4 attributes for the wilderness area and those values are binary
    # In fact they have only attribute valued 1 and the others are 0 so if we delete them and create a new attribute with int type, the data set will be more precise
    # Get the type number of soil and create it into the new attribute "Soil".
    # Do same thing as "Wilderness_Area"
    data['Soil'] = 0
    for i in range(1, 41):
        data['Soil'] = data['Soil'] + i * data['Soil_Type' + str(i)]
    data['Wilderness_Area'] = 0
    for i in range(1, 5):
        data['Wilderness_Area'] = data['Wilderness_Area'] + i * data['Wilderness_Area' + str(i)]
    for i in range(1, 41):
        data = data.drop(['Soil_Type' + str(i)], axis=1)
    for i in range(1, 5):
        data = data.drop(['Wilderness_Area' + str(i)], axis=1)
    return data

# Get the features for training
def get_features():
    return ['Elevation', 'Aspect', 'Slope', 'Horizontal_Distance_To_Hydrology', 'Vertical_Distance_To_Hydrology',
            'Horizontal_Distance_To_Roadways', 'Hillshade_9am', 'Hillshade_Noon', 'Hillshade_3pm',
            'Horizontal_Distance_To_Fire_Points',
            'Ele_minus_VDH', 'Ele_plus_VDH', 'Distanse_to_Hydrolody', 'Hydro_plus_Fire', 'Hydro_minus_Fire',
            'Hydro_plus_Road',
            'Hydro_minus_Road', 'Fire_plus_Road', 'Fire_minus_Road', 'Soil', 'Wilderness_Area']

train_df = change_feature(train_df)
test_df = change_feature(test_df)

features = get_features()

# Get train set's X and Y
x_train = train_df[:][features].values
y_train = train_df['Cover_Type'].values

# Get test set's id and X
test_id = test_df['Id']
x_test = test_df[:][features].values

# Use the ExtraTreesClassifier
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(max_features=0.3, n_estimators=500)

# Training
clf.fit(x_train, y_train)

# Predicting
print("Begin")
output = clf.predict(x_test)
print("Over")

# Get the result and save it into a csv file
result = np.c_[test_id.astype(int), output.astype(int)]
df_result = pd.DataFrame(result[:,0:2], columns=['Id', 'Cover_Type'])
df_result.to_csv('all/forest.csv', index=False)






<class 'pandas.core.frame.DataFrame'>
RangeIndex: 528720 entries, 0 to 528719
Data columns (total 56 columns):
Id                                    528720 non-null int64
Elevation                             528720 non-null int64
Aspect                                528720 non-null int64
Slope                                 528720 non-null int64
Horizontal_Distance_To_Hydrology      528720 non-null int64
Vertical_Distance_To_Hydrology        528720 non-null int64
Horizontal_Distance_To_Roadways       528720 non-null int64
Hillshade_9am                         528720 non-null int64
Hillshade_Noon                        528720 non-null int64
Hillshade_3pm                         528720 non-null int64
Horizontal_Distance_To_Fire_Points    528720 non-null int64
Wilderness_Area1                      528720 non-null int64
Wilderness_Area2                      528720 non-null int64
Wilderness_Area3                      528720 non-null int64
Wilderness_Area4                      528720 non-